Job9/Job9/urls.py
"""
Definition of urls for Job5.
"""

from datetime import datetime
from django.conf.urls import url
import django.contrib.auth.views

import app.forms
import app.views

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = [
    # Examples:
    url(r'^$', app.views.home, name='home'),
    url(r'^contact$', app.views.contact, name='contact'),
    url(r'^about$', app.views.about, name='about'),
    url(r'^links$', app.views.links, name='links'),
    url(r'^profile$', app.views.profile, name='profile'),
    url(r'^registration$', app.views.registration, name='registration'),
    url(r'^blog$', app.views.blog, name='blog'),
    url(r'^(?P<parametr>\d+)/$', app.views.blogpost, name='blogpost'),
    url(r'^newpost$', app.views.newpost, name='newpost'),
    url(r'^videopost$', app.views.videopost, name='videopost'),
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Авторизация',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

Job9/app/forms.py
"""
Definition of forms.
"""

from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import ugettext_lazy as _
from django.db import models
from .models import Comment
from .models import Blog

class BootstrapAuthenticationForm(AuthenticationForm):
    """Authentication form which uses boostrap CSS."""
    username = forms.CharField(max_length=254,
                               widget=forms.TextInput({
                                   'class': 'form-control',
                                   'placeholder': 'Имя пользователя'}))
    password = forms.CharField(label=_("Password"),
                               widget=forms.PasswordInput({
                                   'class': 'form-control',
                                   'placeholder':'Пароль'}))

class profileForm(forms.Form):
    name = forms.CharField(label='Ваше имя', min_length=2, max_length=100)
    city = forms.CharField(label='Ваш город', min_length=2, max_length=100)
    functionality = forms.ChoiceField(
        label='Оцените функциональность сайта',
        choices=[
            ('1', 'Отлично'),
            ('2', 'Хорошо'),
            ('3', 'Удовлетворительно'),
            ('4', 'Неудовлетворительно')
        ],
        widget=forms.RadioSelect,
        initial=1
    )
    design = forms.ChoiceField(
        label='Оцените дизайн сайта',
        choices=[
            ('1', 'Отлично'),
            ('2', 'Хорошо'),
            ('3', 'Удовлетворительно'),
            ('4', 'Неудовлетворительно')
        ],
        initial=1
    )
    notice = forms.BooleanField(label='Получать новости сайта по e-mail?', required=False)
    email = forms.EmailField(label='Ваш e-mail', min_length=7)
    message = forms.CharField(label='Пожелания', widget=forms.Textarea(attrs={'rows':12, 'cols':20}))
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {'text': 'Комментарий'}

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = {'title', 'description', 'content', 'posted', 'author', 'image'}
        labels = {'title': 'Заголовок', 'description': 'Краткое описание', 'content': 'Содержание', 'posted': 'Дата', 'author': 'Автор', 'image': 'Путь к картинке'}

Job9/app/templates/app/about.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<p>Mopar Garage Pskov - это место где вы всегда сможете приобрести уникальные запчасти для Ваших машин, получить много информации, а так же отремонтировать своего "Железного коня".</p>

{% endblock %}

Job9/app/templates/app/blog.html
{% extends 'app/layout.html' %}

{% block content %}
<h2>{{ title }}</h2><br />

{% for post in posts %}
<hr />
<div class="">
    <h2>{{ post.title }}</h2>
    <h4>{{ post.posted }}</h4>
    <p>{{ post.description }}</p>
    <p><a href="{% url 'blogpost' parametr=post.id %}">Читать далее</a></p>
</div>
{% endfor %}

{% endblock %}

Job9/app/templates/app/blogpost.html
{% extends 'app/layout.html' %}
{% block content %}
<h2>{{ post_1.title }}</h2>
{% if post_1.image and post_1.image.url != '/media/temp.jpg' %}
<img src="{{ post_1.image.url }}" alt="Картинка" width="300" height="200" />
{% endif %}

<p>{{ post_1.content|linebreaksbr }}</p>

{% if user.is_authenticated %}
    <h3>Добавить комментарий</h3>
    <form method="post">
        {% csrf_token %}
        <div>
            {{ form.as_p }}
            <button type="submit" class="save btn btn-default">Отправить комментарий</button>
        </div>
    </form>
{% else %}
    <h3>Для добавления своего комментария, пожалуйста, авторизуйтесь</h3>
{% endif %}

{% for comment in comments %}
    <hr />
    <h6>{{ comment.date }}</h6>
    <h5>{{ comment.author }}</h5>
    <p>{{ comment.text|linebreaksbr }}</p>
{% endfor %}

<p><a href="{% url 'blog' %}">Назад</a></p>
{% endblock %}

Job9/app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<address>
    Mopar Garage Pskov<br />
    180006, г. Псков, Ул. Ипподромная д. 129<br />
    <abbr >Телефон:</abbr>
    8 (951) 756-76-78
    <abbr> Месенджеры:</abbr>
    WhatsApp, Viber
</address>

<address>
    <strong>Электронная почта:</strong>   <a href="mailto:Burov.alexey.mihaylovich@gmail.com">Mopar Garage</a><br />
    </address>

{% endblock %}

Job9/app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Mopar Garage Pskov</h1>
    <p class="lead">Место где Вы всегда получите то, что так давно искали! Всегда есть самое редкое и ценное для ваших машин. </p>
    <p><a href="https://www.drive2.ru/users/jasty/" class="btn btn-primary btn-large">Узнать больше &raquo;</a></p>
</div>

{% load staticfiles %}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="5000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="{% static 'app/content/banner1.jpg' %} " alt="Первый слайд" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Встреча 2019 года на Воробьевых горах.
                    <a class="btn btn-default" href="https://www.drive2.ru/l/544143357857759818/">
                        Читать далее
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="{% static 'app/content/banner2.jpg' %}" alt="Второй слайд"  class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Встреча 2019 года на Воробьевых горах (Продолжение).
                    <a class="btn btn-default" href="https://www.drive2.ru/l/544196134415892757">
                        Читать далее
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src=" {% static 'app/content/banner3.jpg' %} " alt="Третий слайд"  class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Открытие сезона - 20 апреля 2019 года.
                    <a class="btn btn-default" href="https://www.drive2.ru/l/530477802714038589/">
                        Читать далее
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Chrysler 300M</h2>
        <p>
            Все о существующих модификациях данной машины:
            <ul>
                <li>Chrysler 300M Base;</li>
                <li>Chrysler 300M Special;</li>
                <li>Chrysler 300M Pro-am;</li>
                <li>Chrysler 300M Startech;</li>
                <li>Chrysler 300M Lorinser;</li>
                <li>Chrysler 300M Platinum.</li>
            </ul>
        </p>
        <p><a class="btn btn-default" href="https://ru.wikipedia.org/wiki/Chrysler_300M">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-3">
        <h2>Chrysler Concorde</h2>
        <p>
            Все о существующих модификациях данной машины:
            <ul>
                <li>Chrysler Concorde LX;</li>
                <li>Chrysler Concorde 2002-2004 limited;</li>
                <li>Chrysler Concorde LXi.</li>
                       </ul>
        </p>
        <p><a class="btn btn-default" href="https://ru.wikipedia.org/wiki/Chrysler_Concorde">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-3">
        <h2>Chrysler LHS</h2>
        <p>
            Все о существующих модификациях данной машины:
            <ul>
                                <li>Chrysler LHS 1998-2001.</li>
            </ul>
        </p>
        <p><a class="btn btn-default" href="https://ru.wikipedia.org/wiki/Chrysler_LHS">Узнать больше &raquo;</a></p>
    </div>
    <div class="col-md-3">
        <h2>Chrysler/Dodge Intrepid </h2>
        <p>
            Все о существующих модификациях данной машины:
            <ul>
                <li>Chrysler/Dodge Intrepid SE;</li>
                <li>Chrysler/Dodge Intrepid ES;</li>
                <li>Chrysler/Dodge Intrepid R/T;</li>
                <li>Chrysler/Dodge Intrepid SXT.</li>
                
            </ul>
        </p>
        <p><a class="btn btn-default" href="https://ru.wikipedia.org/wiki/Dodge_Intrepid">Узнать больше &raquo;</a></p>
    </div>
</div>

{% endblock %}

Job9/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }} - Mopar Garage Pskov</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand"><img src="{% static 'app/content/logo.png' %}" alt="Логотип" height="50"></a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'home' %}">Главная</a></li>
                    <li><a href="{% url 'about' %}">О нас</a></li>
                    <li><a href="{% url 'contact' %}">Контакты</a></li>
                    <li><a href="{% url 'profile' %}">Обратная связь</a></li>
                    <li><a href="{% url 'links' %}">Полезные ресурсы</a></li>
                    <li><a href="{% url 'blog' %}">Блог</a></li>
                    {% if user.is_superuser %}
                    <li><a href="{% url 'newpost' %}">Добавление статьи</a></li>
                    {% endif %}
                    <li><a href="{% url 'videopost' %}">Видео</a></li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {{ year }} - Mopar Garage Pskov</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

Job9/app/templates/app/links.html
{% extends "app/layout.html" %}

{% block content %}

{% load staticfiles %}

<h2>{{ title }}.</h2>
<h3>{{ message }}</h3>

<a href="https://vk.com/club12904995"><img src="{% static 'app/content/300m.jpg' %}" alt="vk.com/club12904995" height="100" /></a>
<a href="http://www.chrysler-dodge.ru/"><img src="{% static 'app/content/Club.jpg' %}" alt="chrysler-dodge.ru" height="100" /></a>
<a href="http://www.ravtoby.ru/"><img src="{% static 'app/content/RAVTO.jpg' %}" alt="www.ravtoby.ru" height="100" /></a>

{% endblock %}

Job9/app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Используйте локальную учётную запись, чтобы войти.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">Имя пользователя</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Пароль</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Войти" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Пожалуйста, введите правильные имя пользователя и пароль.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

Job9/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">Привет, {{ user.username }}!</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    {% if not user.is_authenticated %}
        <li><a href="{% url 'registration' %}">Регистрация</a></li>
    {% endif %}
    <li><a href="{% url 'login' %}">Войти</a></li>
</ul>

{% endif %}

Job9/app/templates/app/newpost.html
{% extends 'app/layout.html' %}

{% block content %}

<h3>Добавить статью</h3>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div>
        {{ blogform.as_p }}
        <button type="submit" class="save btn btn-default">Сохранить статью</button>
    </div>
</form>

{% endblock %}

Job9/app/templates/app/profile.html
{% extends "app/layout.html" %}
{% block content %}
{% if form != None %}
<br />
<h2>Обратная связь</h2><br />
<div>
    <form method="post">
        {% csrf_token %}
        <label for="{{ form.name.id_for_label }}">{{ form.name.label }}:</label>
        {{ form.name }}<br /><br />
        <label for="{{ form.city.id_for_label }}">{{ form.city.label }}:</label>
        {{ form.city }}<br /><br />
        <label for="{{ form.functionality.id_for_label }}">{{ form.functionality.label }}:</label>
        {{ form.functionality }}<br /><br />
        <label for="{{ form.design.id_for_label }}">{{ form.design.label }}:</label>
        {{ form.design }}<br /><br />
        <label for="{{ form.notice.id_for_label }}">{{ form.notice.label }}:</label>
        {{ form.notice }}<br /><br />
        <label for="{{ form.email.id_for_label }}">{{ form.email.label }}:</label>
        {{ form.email }}<br /><br />
        <label for="{{ form.message.id_for_label }}">{{ form.message.label }}:</label>
        {{ form.message }}<br /><br />
        <input id="submit" type="submit" value="Отправить" />
    </form>
</div>
{% else %}
<br />
<h2>Благодарим за обратную связь!</h2>
<h3>Вы сообщили следующее:</h3>
<ul>
    <li><span>Имя:</span> {{ data.name }}</li>
    <li><span>Город:</span> {{ data.city }}</li>
    <li><span>Функицональность сайта:</span> {{ data.functionality }}</li>
    <li><span>Дизайн сайта:</span> {{ data.design }}</li>
    <li><span>Получать новости сайта по e-mail:</span> {{ data.notice }}</li>
    <li><span>Ваш e-mail:</span> {{ data.email }}</li>
    <li><span>Пожелания:</span> {{ data.message }}</li>
</ul>
{% endif %}
{% endblock %}

{% block scripts %}
<script>
    $('#submit').mouseover(function() {
        $(this).css('color', '#ff8ab1');
    });
    $('#submit').mouseout(function () {
        $(this).css('color', '#000000');
    });
    $('#id_name, #id_city, #id_email, #id_message').focus(function () {
        $(this).css('background-color', '#ff8ab1');
    });
    $('#id_name, #id_city, #id_email, #id_message').blur(function () {
        $(this).css('background-color', '#57b0ff');
    });
</script>
{% endblock %}

Job9/app/templates/app/registration.html
{% extends "app/layout.html" %}
{% block content %}
<h2>Регистрация пользователя</h2>
<form method="post">
    {% csrf_token %}
    <div>
        {{ regform.as_p }}
        <button type="submit" class="save btn btn-default">
            Зарегистрироваться
        </button>
    </div>
</form>
{% endblock %}

Job9/app/templates/app/videopost.html
{% extends 'app/layout.html' %}

{% block content %}

<div>
    <h1>Разгон 0-100 Chrysler 300m 3.5L </h1>
    <video src="/media/video1.mp4" controls="controls" width="400" heigth="300" poster="/media/poster1.jpg"></video>
</div>
<hr />
<div>
    <h1>Комерческая реклама 2002 год. </h1>
    <video src="/media/video2.mp4" controls="controls" width="400" heigth="300" poster="/media/poster2.jpg"></video>
</div>

{% endblock %}